### ISSUE TITLE
Game components

### ISSUE THREAD

**Issue by Hoodgail** [sicaro-organization/issues#5]
add game components to the editor: Spawn points etc

**Comment by Hoodgail** [comment]
# Progress

![image](https://user-images.githubusercontent.com/45743294/208569047-9151045f-95d5-4412-a2ba-227c0791b247.png)

**Comment by Armaccord** [comment]
![208569047-9151045f-95d5-4412-a2ba-227c0791b247](https://user-images.githubusercontent.com/114373486/208571641-b07613e9-facd-427d-b20c-c3c2ff07933b.png)
Spawn Properties should be on top of the hierarchy, as well as any other component dependent properties.
